name: CI

on: pull_request

jobs:
  CI:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install
      run: npm install
    - name: Test
      run: npm run test
    - name: Build
      run: npm run-script build
    
